


services:
  web:
    build: .
    ports:
      - "5033:5000"
    depends_on:
      - redis
      - db
    environment:
      - FLASK_ENV=development
      - REDIS_HOST=redis
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=mydatabase

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  db:
    image: "mysql:8.0"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro