name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies      
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: pytest

  build-and-push-image:
    if: ${{github.event_name=="push"}}
   runs-on: ubuntu-latest
   needs: test 
   steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCER_HUB_USERNAMES}}
        password: ${{ secrets.DOCKERHUB_TOKENS}}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: |
          majedz/flask-app:latest
          majedz/flask-app:${{ github.sha }}
          
          