name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build -t flask-app .

      - name: Run tests
        run: docker run flask-app pytest # Replace `pytest` with your actual test command

  build-and-push-image:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCER_HUB_USERNAME }}
          password: ${{ secrets.DOCER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build -t flask-app .
          docker tag flask-app majedz/flask-app:latest

      - name: Push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            majedz/flask-app:latest
            majedz/flask-app:${{ github.sha }}